### ISSUE TITLE
Application error at startup

### ISSUE THREAD

**Issue by LS-Kaution** [renejfc/afkursor#3]
I recently received help to use afkursor due to compatibility problems in Windows. But just now I have a new problem which is:

```
bunx afkursor@0.0.3
🔍 @nut-tree/nut-js [2/2]
error: package "@nut-tree/nut-js" not found registry.npmjs.org/@nut-tree%2fnut-js 404
error: @nut-tree/nut-js@^4.1.0 failed to resolve
```

I'm sure the error is because of a library rename or something related to it.

I appreciate any guidance or solution you can provide me to overcome this problem.

**Comment by renejfc** [comment]
I used the `@nut-tree/nut-js` package on versions prior to `v0.0.4`, and unfortunately the maintainer ["gave up"](https://arc.net/l/quote/kzrvpbmp) on the package, at least the public ones:

> All of my packages around nut.js will cease to exist publicly on npm. Ready-to-use packages will only be available through the private nut.js package registry, which requires an active subscription to be used.

So for now it'll only work on versions `>= 0.0.4`, which also [doesn't work on Windows](https://github.com/renejfc/afkursor/issues/2) (yet)
